#!/bin/sh

EXEC=phpdoc

echo "Looking for phpdoc command ..."
${EXEC} -V

if [ $? != 0 ]
    then
        echo "Looking for phpdoc in vendor/ ..."
        EXEC="vendor/phpdocumentor/phpdocumentor/bin/phpdoc"
        ${EXEC} -V
fi

if [ $? != 0 ]
    then
        echo "phpdoc not found." 1>&2
        exit 1
fi

# run unit tests
${EXEC}

exit $?
